import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-dme-rental-reimbursement-recovery",
  "engine": "recovery",
  "title": "DME Rental Reimbursement Recovery",
  "shortTitle": "DME Rental Reimbursement Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through dme rental reimbursement recovery",
  "industry": "Durable Medical Equipment Revenue Integrity",
  "uiPort": 4602,
  "apiPort": 5602,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "DME Rental Reimbursement Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Payer Paid Amount",
    "expectedLabel": "Supported Rental Reimbursement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "DME Rental Reimbursement Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("equipment-hcpcs-registry","DRR01","Equipment HCPCS registry","Execute equipment hcpcs registry using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed equipment hcpcs registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Equipment HCPCS registry Reference","text","DRR01-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("patient-order-tracking","DRR02","Patient order tracking","Execute patient order tracking using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed patient order tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Patient order tracking Reference","text","DRR02-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("coverage-necessity-rules","DRR03","Coverage necessity rules","Execute coverage necessity rules using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed coverage necessity rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Coverage necessity rules Reference","text","DRR03-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("proof-of-delivery-control","DRR04","Proof-of-delivery control","Execute proof-of-delivery control using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed proof-of-delivery control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Proof-of-delivery control Reference","text","DRR04-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("prior-authorization","DRR05","Prior authorization","Execute prior authorization using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed prior authorization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Prior authorization Reference","text","DRR05-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("capped-rental-tracking","DRR06","Capped rental tracking","Execute capped rental tracking using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed capped rental tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Capped rental tracking Reference","text","DRR06-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("purchase-versus-rental-calculation","DRR07","Purchase versus rental calculation","Execute purchase versus rental calculation using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed purchase versus rental calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Purchase versus rental calculation Reference","text","DRR07-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("competitive-bidding-adjustment","DRR08","Competitive bidding adjustment","Execute competitive bidding adjustment using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed competitive bidding adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Competitive bidding adjustment Reference","text","DRR08-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("oxygen-supply-replenishment","DRR09","Oxygen supply replenishment","Execute oxygen supply replenishment using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed oxygen supply replenishment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Oxygen supply replenishment Reference","text","DRR09-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("same-or-similar-validation","DRR10","Same-or-similar validation","Execute same-or-similar validation using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed same-or-similar validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Same-or-similar validation Reference","text","DRR10-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("claim-generation","DRR11","Claim generation","Execute claim generation using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed claim generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Claim generation Reference","text","DRR11-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("denial-appeal-workflow","DRR12","Denial appeal workflow","Execute denial appeal workflow using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed denial appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Denial appeal workflow Reference","text","DRR12-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("asset-return-tracking","DRR13","Asset return tracking","Execute asset return tracking using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed asset return tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Asset return tracking Reference","text","DRR13-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("remittance-reconciliation","DRR14","Remittance reconciliation","Execute remittance reconciliation using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed remittance reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Remittance reconciliation Reference","text","DRR14-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]}),
feature("product-payer-profitability","DRR15","Product payer profitability","Execute product payer profitability using equipment records, HCPCS codes, patient orders, medical necessity, delivery evidence, authorizations, rental months, fee schedules, replenishment, claims, returns, and remittances.","Produce a governed product payer profitability decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Patient Equipment","text","Supplier / Patient Equipment · Standard Case"],["caseReference","Product payer profitability Reference","text","DRR15-2026-001"],["paidAmount","Payer Paid Amount","currency",623500],["expectedAmount","Supported Rental Reimbursement","currency",735730],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Equipment HCPCS registry case","Patient order tracking case","Coverage necessity rules case","Proof-of-delivery control case","Prior authorization case"]})
]);
